<?php
return [
    // 是否开启api log 日志记录,测试没效果
    'debug' => true,
    // api接口token有效期 默认2天
    'user.accessTokenExpire' => 2 * 24 * 3600,
    // token有效期是否验证 默认不验证
    'user.accessTokenValidity' => false,
    // 不需要token验证的方法
    'user.optional' => [
        '*',
        'login',
        'recover-wallet',
        'refresh',
        'coin-list',
        'ticker',
        'get-version',
        'mobile-varcode',
        'register',
        'sign',
        'user-info',
        'invite-info',
        'invite-rank',
        'api-key',
        'set-real',
        'upload-image',
        'get-info',
        'password-edit',
        'nickname-edit',
        'bind-email',
        'bind-phone',
        'auth',
        'market',
        'market-login',
        'balance',
        'order-limit',
        'coin-text',
        'cancel-order',
        'message-list',
        'forget-password',
        'start-page',
        'cate',
        'turn-out',
        'coin-list',
        'market-list',
        'recharge-details',
        'find-user',
        'get-token',
        'init-pc',
        'trade-add',
        'trade-find',
        'trade-delete',
        'merchants',
        'generate-address',
        'add-address',
        'get-address',
        'del-address',
        'edit-address',
        'image',
        'video',
        'info',
        'forget-password-phone',
        'withdraw-prepare',
        'robot-list',
        'qrcode',
        'email-register',
        'email-varcode',
        'email-sign',
        'email-forget-password',
        'notify',
        'up',
        'summary',
        'test',
        'add',
    ],
    // 速度控制6秒内访问3次，注意，数组的第一个不要设置1，设置1会出问题，一定要大于2，譬如下面  6秒内只能访问三次
    'user.rateLimit' => [10000, 1],
];